spring.application.name=demo
# 引入其他配置文件
spring.config.import=classpath:param.yml

# 修改日志级别
logging.level.com.example.demo=DEBUG

# 数据库连接配置
spring.datasource.url=jdbc:mysql://localhost:3306/znkf?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=yexinke
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis基础配置
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.default-statement-timeout=30
